version: "3.8"
services:
  mongo:
    image: mongo:6
    ports: ["27017:27017"]

  backend:
    build: ./backend
    ports: ["8080:8080"]
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/healthcare
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports: ["3000:80"]
    depends_on:
      - backend
